(deftheme ample
  "Created 2020-12-21.")

(custom-theme-set-variables
 'ample
 '(ansi-color-names-vector ["#454545" "#cd5542" "#6aaf50" "#baba36" "#5180b3" "#ab75c3" "#bdbc61" "#bdbdb3"]))

(custom-theme-set-faces
 'ample
 '(cursor ((t (:foreground "gray13" :background "#f57e00"))))
 '(fringe ((t (:background "#1f1f1f"))))
 '(link ((t (:foreground "#68a5e9" :underline t))))
 '(region ((t (:background "steel blue"))))
 '(font-lock-builtin-face ((t (:foreground "#528fd1"))))
 '(font-lock-comment-face ((t (:foreground "#757575"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#656565"))))
 '(font-lock-function-name-face ((t (:foreground "#6aaf50"))))
 '(font-lock-keyword-face ((t (:foreground "#5180b3"))))
 '(font-lock-string-face ((t (:foreground "#bdbc61"))))
 '(font-lock-preprocessor-face ((t (:foreground "#dF9522"))))
 '(font-lock-type-face ((t (:foreground "#cd5542"))))
 '(font-lock-constant-face ((t (:foreground "#ab75c3"))))
 '(font-lock-warning-face ((t (:foreground "red" :bold t))))
 '(font-lock-variable-name-face ((t (:foreground "#baba36"))))
 '(font-lock-doc-face ((t (:foreground "#7d7c61"))))
 '(mode-line-inactive ((t (:background "#454545" :foreground "cornsilk4"))))
 '(mode-line ((t (:background "cornsilk4" :foreground "#252525"))))
 '(header-line ((t (:background "#bdbdb3" :foreground "gray13"))))
 '(button ((t (:foreground "#68a5e9" :background nil :underline t))))
 '(isearch ((t (:background "#5180b3" :foreground "gray13"))))
 '(lazy-highlight ((t (:background "gray13" :foreground "#ab75c3" :underline t))))
 '(ace-jump-face-background ((t (:inherit font-lock-comment-face))))
 '(ace-jump-face-foreground ((t (:foreground "#dF9522"))))
 '(vertical-border ((t (:background "#454545" :foreground "#252525"))))
 '(minibuffer-prompt ((t (:foreground "#fffe0a" :bold t :background nil))))
 '(compilation-error ((t (:foreground "#cd5542" :bold t))))
 '(compilation-warning ((t (:foreground "#dF9522" :bold t))))
 '(compilation-info ((t (:foreground "#6aaf50" :bold t))))
 '(comint-highlight-prompt ((t (:foreground "#6aaf50"))))
 '(undo-tree-visualizer-active-branch-face ((t (:inherit default))))
 '(undo-tree-visualizer-default-face ((t (:inherit font-lock-comment-face))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#cd5542" :background nil))))
 '(show-paren-match ((t (:foreground nil :background "#656565"))))
 '(show-paren-mismatch ((t (:inherit error))))
 '(error ((t (:foreground "red"))))
 '(ido-only-match ((t (:foreground "#6aaf50"))))
 '(ido-first-match ((t (:foreground "#5180b3"))))
 '(ido-incomplete-regexp ((t (:foreground "#cd5542"))))
 '(ido-subdir ((t (:foreground "#baba36"))))
 '(diff-added ((t (:foreground nil :background "#284828"))))
 '(diff-changed ((t (:foreground nil :background "#484828"))))
 '(diff-removed ((t (:foreground nil :background "#482828"))))
 '(diff-context ((t (:foreground "#757575" :background nil))))
 '(diff-file-header ((t (:foreground "gray13" :background "grey60" :bold t))))
 '(diff-function ((t (:foreground "gray13" :background "grey50"))))
 '(diff-header ((t (:foreground "gray13" :background "grey50"))))
 '(diff-hunk-header ((t (:foreground "gray13" :background "grey50"))))
 '(diff-index ((t (:foreground "gray13" :background "grey50"))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-indicator-changed ((t (:inherit diff-changed))))
 '(diff-indicator-removed ((t (:inherit diff-removed))))
 '(diff-nonexistent ((t (:foreground nil :background "grey70"))))
 '(diff-refine-added ((t (:foreground nil :background "#649694"))))
 '(diff-refine-changed ((t (:foreground nil :background "#8f8f40"))))
 '(diff-refine-removed ((t (:foreground nil :background "#694949"))))
 '(org-done ((t (:foreground "#6aaf50" :background nil))))
 '(org-todo ((t (:foreground "#cd5542" :background nil))))
 '(org-hide ((t (:foreground "gray13" :background nil))))
 '(message-cited-text ((t (:inherit font-lock-comment-face))))
 '(message-header-cc ((t (:foreground "#528fd1" :background nil :bold t))))
 '(message-header-name ((t (:foreground "#dF9522" :background nil))))
 '(message-header-newsgroups ((t (:foreground "#7d7c61" :background nil :bold t))))
 '(message-header-other ((t (:foreground "#5180b3" :background nil))))
 '(message-header-subject ((t (:foreground "#bdbc61" :background nil))))
 '(message-header-to ((t (:foreground "#baba36" :background nil :bold t))))
 '(message-header-xheader ((t (:foreground "#ab75c3" :background nil))))
 '(message-mml ((t (:foreground "#7d7c61" :background nil))))
 '(gnus-group-mail-1 ((t (:foreground "#5180b3" :background nil :bold t))))
 '(gnus-group-mail-1-empty ((t (:foreground "#5180b3" :background nil))))
 '(gnus-group-mail-2 ((t (:foreground "#68a5e9" :background nil :bold t))))
 '(gnus-group-mail-2-empty ((t (:foreground "#68a5e9" :background nil))))
 '(gnus-group-mail-3 ((t (:foreground "#528fd1" :background nil :bold t))))
 '(gnus-group-mail-3-empty ((t (:foreground "#528fd1" :background nil))))
 '(gnus-group-mail-low ((t (:foreground "#baba36" :background nil :bold t))))
 '(gnus-group-mail-low-empty ((t (:foreground "#baba36" :background nil))))
 '(gnus-group-news-1 ((t (:foreground "PaleTurquoise" :background nil :bold t))))
 '(gnus-group-news-1-empty ((t (:foreground "PaleTurquoise" :background nil))))
 '(gnus-group-news-2 ((t (:foreground "turquoise" :background nil :bold t))))
 '(gnus-group-news-2-empty ((t (:foreground "turquoise" :background nil))))
 '(gnus-group-news-3 ((t (:foreground nil :background nil :bold t))))
 '(gnus-group-news-3-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-4 ((t (:foreground nil :background nil :bold t))))
 '(gnus-group-news-4-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-5 ((t (:foreground nil :background nil :bold t))))
 '(gnus-group-news-5-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-6 ((t (:foreground nil :background nil :bold t))))
 '(gnus-group-news-6-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-low ((t (:foreground "DarkTurquoise" :background nil :bold t))))
 '(gnus-group-news-low-empty ((t (:foreground "DarkTurquoise" :background nil))))
 '(gnus-splash ((t (:foreground "#cccccc" :background nil))))
 '(gnus-summary-cancelled ((t (:foreground "yellow" :background "black"))))
 '(gnus-summary-high-ancient ((t (:foreground "SkyBlue" :background nil :bold t))))
 '(gnus-summary-high-read ((t (:foreground "PaleGreen" :background nil :bold t))))
 '(gnus-summary-high-ticked ((t (:foreground "pink" :background nil :bold t))))
 '(gnus-summary-high-undownloaded ((t (:foreground "LightGray" :background nil :bold t))))
 '(gnus-summary-high-unread ((t (:foreground nil :background nil :bold t))))
 '(gnus-summary-low-ancient ((t (:foreground "SkyBlue" :background nil))))
 '(gnus-summary-low-read ((t (:foreground "PaleGreen" :background nil))))
 '(gnus-summary-low-ticked ((t (:foreground "pink" :background nil))))
 '(gnus-summary-low-undownloaded ((t (:foreground "LightGray" :background nil))))
 '(gnus-summary-low-unread ((t (:foreground nil :background nil))))
 '(gnus-summary-normal-ancient ((t (:inherit default))))
 '(gnus-summary-normal-read ((t (:foreground "#6aaf50" :background nil))))
 '(gnus-summary-normal-ticked ((t (:foreground "#dF9522" :background nil))))
 '(gnus-summary-normal-undownloaded ((t (:foreground "#656565" :background nil))))
 '(gnus-summary-normal-unread ((t (:foreground "#528fd1" :background nil))))
 '(gnus-summary-selected ((t (:foreground nil :background nil :underline t))))
 '(trailing-whitespace ((t (:background "white" :bold t))))
 '(custom-button ((t (:foreground nil :background nil))))
 '(custom-button-mouse ((t (:foreground nil :background nil))))
 '(custom-button-pressed ((t (:foreground nil :background nil))))
 '(custom-button-pressed-unraised ((t (:foreground "#ab75c3" :background nil))))
 '(custom-button-unraised ((t (:foreground nil :background nil))))
 '(custom-changed ((t (:foreground "#cd5542" :background nil))))
 '(custom-comment ((t (:foreground "gray13" :background "#baba36"))))
 '(custom-comment-tag ((t (:foreground "#bdbdb3" :background nil))))
 '(custom-documentation ((t (:foreground nil :background nil))))
 '(custom-face-tag ((t (:foreground "#528fd1" :background nil))))
 '(custom-group-subtitle ((t (:foreground nil :background nil :bold t))))
 '(custom-group-tag ((t (:foreground "#528fd1" :background nil :bold t))))
 '(custom-group-tag-1 ((t (:foreground "#baba36" :background nil :bold t))))
 '(custom-invalid ((t (:foreground "gray13" :background "#cd5542"))))
 '(custom-link ((t (:inherit button))))
 '(custom-modified ((t (:foreground "#cd5542" :background nil))))
 '(custom-rogue ((t (:foreground "#baba36" :background "gray13"))))
 '(custom-saved ((t (:foreground nil :background nil :underline t))))
 '(custom-set ((t (:foreground "#bdbdb3" :background "#656565"))))
 '(custom-state ((t (:foreground "#6aaf50" :background nil))))
 '(custom-themed ((t (:foreground "#cd5542" :background nil))))
 '(custom-variable-button ((t (:foreground nil :background nil :underline t :bold t))))
 '(custom-variable-tag ((t (:foreground "#528fd1" :background nil :bold t))))
 '(custom-visibility ((t (:inherit button))))
 '(widget-field ((t (:foreground "#bdbdb3" :background "#656565"))))
 '(default ((t (:foreground "#bdbdb3" :background "gray13")))))

(provide-theme 'ample)
