* Basic things
** Tidier UI
#+begin_src emacs-lisp
(setq inhibit-splash-screen t)

(tool-bar-mode 0)
(scroll-bar-mode 0)
(display-battery-mode 0)
#+end_src

** Shorter prompt
#+begin_src emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
** Scrolling behaviour
Avoids jumping half-a-screen when cursor reaches buttom of screen

#+begin_src emacs-lisp
(setq scroll-conservatively 10000)
#+end_src
** Default tab settings
Don't indent with tabs, and make tab-width 4 just-in-case

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq tab-width 4)
#+end_src
** C++ indentation
if(blah)
{
    etc;
}
#+begin_src emacs-lisp
(setq-default c-basic-offset 4)
(setq-default c-default-style "bsd") ; or k&r?
#+end_src
** Quieter visual bell
Message in minibuf on bell, instead of system beep etc
#+begin_src emacs-lisp
(setq ring-bell-function (lambda () (message "*beep*")))
#+end_src
*** Flash scroll-lock LED (disabled)
#+begin_src emacs-lisp
;(setq ring-bell-function (lambda ()
;  (call-process-shell-command "xset led 3; xset -led 3" nil 0 nil)))
#+end_src
** Avoid FS mess
*** Move autosave/backup files to ~/.emacs.d/autosaves and ~/.emacs.d/backups

#+begin_src emacs-lisp
(setq backup-directory-alist
      `((".*" . , "~/.emacs.d/backups/")))
(setq auto-save-file-name-transforms
      `((".*" ,"~/.emacs.d/autosaves/" t)))
#+end_src

*** Ensure directory exists
#+begin_src emacs-lisp
(make-directory "~/.emacs.d/backups" t)
(make-directory "~/.emacs.d/autosaves" t)
#+end_src
*** Remove old backups
Remove backups older than one week

#+begin_src emacs-lisp
(message "Deleting old backup files...")
(let ((week (* 60 60 24 7))
      (current (float-time (current-time))))
  (dolist (file (directory-files temporary-file-directory t))
    (when (and (backup-file-name-p file)
               (> (- current (float-time (fifth (file-attributes file))))
                  week))
      (message file)
      (delete-file file))))
#+end_src

** Empty default scratch buffer
#+begin_src emacs-lisp
(setq initial-scratch-message "")
#+end_src

** Recent files
*** Enable recentf mode
Also limit to 25 files
#+begin_src emacs-lisp
(require 'recentf)
(setq recentf-max-menu-items 25)
#+end_src

*** Don't clean up recent files
It potentially access network drives, which could trigger tramp,
http://stackoverflow.com/questions/880625

#+begin_src emacs-lisp
(setq recentf-auto-cleanup 'never)
#+end_src

*** Bind to C-x C-r
"C-x r" would be better, but it interfers with "C-x r k" for kill-rectangle
#+begin_src emacs-lisp
(global-set-key "\C-x\ \C-r" 'recentf-open-files)
#+end_src
** Guess mode for new buffer
Guess default mode in new buffers from file extension
http://atomized.org/2010/08/scratch-buffers-for-emacs/

#+begin_src emacs-lisp
(setq default-major-mode
      (lambda ()
        (let ((buffer-file-name (or buffer-file-name (buffer-name))))
          (set-auto-mode))))
#+end_src
** uniqify buffer names
Replace useless blah.txt<2> with blah.txt<thedirectory>
#+begin_src emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'post-forward-angle-brackets)
#+end_src
** Access killring menu
#+begin_src emacs-lisp
(global-set-key "\C-cy" '(lambda ()
   (interactive)
   (popup-menu 'yank-menu)))
#+end_src
** Cycle buffers with F1/F2
#+begin_src emacs-lisp
(global-set-key [f1] 'previous-buffer)
(global-set-key [f2] 'next-buffer)
#+end_src
** Fullscreen
Only really works on Linux
#+begin_src emacs-lisp
(defun fullscreen (&optional f)
  (interactive)
  (set-frame-parameter f 'fullscreen
                       (if (frame-parameter f 'fullscreen) nil 'fullboth)))

;(add-hook 'after-make-frame-functions 'fullscreen) ; on startup
(global-set-key [f11] 'fullscreen)
#+end_src
** Scrolling
More sane scrolling with OS X mouse/trackpad

#+begin_src emacs-lisp
(global-set-key [wheel-down] (lambda () (interactive) (scroll-up-command 1)))
(global-set-key [wheel-up] (lambda () (interactive) (scroll-down-command 1)))
(global-set-key [double-wheel-down] (lambda () (interactive) (scroll-up-command 2)))
(global-set-key [double-wheel-up] (lambda () (interactive) (scroll-down-command 2)))
(global-set-key [triple-wheel-down] (lambda () (interactive) (scroll-up-command 4)))
(global-set-key [triple-wheel-up] (lambda () (interactive) (scroll-down-command 4)))
#+end_src
* FS navigation
** Use ido for shinier minibuf (C-x b and C-x C-f)
#+begin_src emacs-lisp
(ido-mode 1)
#+end_src

** Ignore files in ido
Ignore .DS_Store and .pyc when finding files

#+begin_src emacs-lisp
(add-to-list 'ido-ignore-files "\\.DS_Store")
(add-to-list 'ido-ignore-files "\\.pyc")
#+end_src


Also OS X "Icon" file: http://stackoverflow.com/q/9053161/745

#+begin_src emacs-lisp
(add-to-list 'ido-ignore-files "Icon\n")
#+end_src
** Prevent ido searching for locations
Disable auto searching for files unless called explicitly, prevents
finding files in random directories automatically

#+begin_src emacs-lisp
(setq ido-auto-merge-delay-time 99999)

(define-key ido-file-dir-completion-map (kbd "C-c C-s")
  (lambda()
    (interactive)
    (ido-initiate-auto-merge (current-buffer))))
#+end_src
* org-mode config
** Enable shift-selection in org
#+begin_src emacs-lisp
(setq org-support-shift-select t)
#+end_src
** auto-mode
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
#+end_src
** babel inline edit
Configure org-mode so that when you edit source code in an indirect
buffer (with C-c '), the buffer is opened in the current window. That
way, your window organization isn't broken when switching.

From http://kieranhealy.org/esk/kjhealy.html

#+begin_src emacs-lisp
(setq org-src-window-setup 'current-window)
#+end_src

* Emacs server
** Start server
#+begin_src emacs-lisp
(server-start)
#+end_src
** Useful bash alias
Jumps to directory of current file (for reference, not evaluated)
http://www.reddit.com/r/emacs/comments/hd3jm/from_my_bashrc_jump_to_emacss_current_directory/#+begin_src bash
alias jm='cd $(emacsclient -e "(with-current-buffer (window-buffer (frame-selected-window)) default-directory)" | '"sed -E 's/(^\")|(\"$)//g')"
#+end_src
* Load path
Get base directory
#+begin_src emacs-lisp
(setq dotfiles-dir (file-name-directory (or load-file-name (buffer-file-name))))
#+end_src

Load base ext/ directories for loose .el files
#+begin_src emacs-lisp
(add-to-list 'load-path (expand-file-name "ext" dotfiles-dir))
#+end_src

Load various directories
#+begin_src emacs-lisp
(dolist (d '("google-maps" "yasnippet-0.6.1c" "smex" "multi-term" "restclient" "magit" "multiple-cursors"))
  (add-to-list 'load-path (expand-file-name d (expand-file-name "ext" dotfiles-dir))))
#+end_src

Theme load-path
#+begin_src emacs-lisp
(add-to-list 'custom-theme-load-path (expand-file-name "ext" dotfiles-dir))
#+end_src
*** TODO func to add to loadpath?
*** TODO Auto-load all directories in ext/?
* Misc modules
** Theme
*** Gunmetal (disabled)
Heavily tweaked gunmetal theme

#+begin_src emacs-lisp
;(require 'color-theme)
;(require 'gunmetal)
;(color-theme-gunmetal)
#+end_src
*** Naquadah
http://julien.danjou.info/blog/2011.html#Naquadah_theme_for_Emacs
#+begin_src emacs-lisp
(require 'naquadah-theme)
#+end_src
** Undo window changes
Undo changes to layout with C-left C-right
#+begin_src emacs-lisp
(winner-mode 1)
#+end_src
** highlight-parentheses
Require module and set nicer colours

http://www.emacswiki.org/emacs/HighlightParentheses

#+begin_src emacs-lisp
(require 'highlight-parentheses)
(setq hl-paren-colors (quote ("firebrick" "lightgreen" "orange" "cyan")))
#+end_src
** cmake-mode
#+begin_src emacs-lisp
(require 'cmake-mode)
(setq auto-mode-alist
      (append '(("CMakeLists\\.txt\\'" . cmake-mode)
                ("\\.cmake\\'" . cmake-mode))
              auto-mode-alist))
#+end_src
** textmate-mode
Require and auto load for .py files

#+begin_src emacs-lisp
(require 'textmate)
(add-hook 'python-mode-hook
'(lambda ()
	(interactive)
	(textmate-mode)))
#+end_src
** Window resizing shortcuts
Super+ctrl+arrows

#+begin_src emacs-lisp
(global-set-key [(super control right)] 'shrink-window-horizontally)
(global-set-key [(super control left)] 'enlarge-window-horizontally)
(global-set-key [(super control up)] 'shrink-window)
(global-set-key [(super control down)] 'enlarge-window)
#+end_src

** Window-jumping shortcuts
#+begin_src emacs-lisp
(require 'windmove)
(windmove-default-keybindings 'super)
#+end_src
** Super+return makes new line after current
#+begin_src emacs-lisp
(defun make-newline-after-current()
  (interactive)
  (end-of-line)
  (newline-and-indent))

(global-set-key [(super return)] 'make-newline-after-current)
#+end_src
** Undo-tree
#+begin_src emacs-lisp
(require 'undo-tree)
#+end_src
** Google maps
Erm.
http://julien.danjou.info/google-maps-el.html
#+begin_src emacs-lisp
;(autoload 'google-maps)
(autoload 'google-maps "google-maps")
#+end_src
** Rainbow
Useful for editing themes and CSS
http://julien.danjou.info/rainbow-mode.html
#+begin_src emacs-lisp
(require 'rainbow-mode)
#+end_src
** yasnippet
*** Load code
#+begin_src emacs-lisp
(require 'yasnippet)
(yas/initialize)
(yas/load-directory (expand-file-name "snippets" (expand-file-name "yasnippet-0.6.1c" (expand-file-name "ext" dotfiles-dir))))
#+end_src
*** Custom snippet dir
#+begin_src emacs-lisp
(yas/load-directory (expand-file-name "snippets" dotfiles-dir))
#+end_src
*** Make it work in org-mode
org-mode's tab overriding prevents yasnippet from working

http://orgmode.org/worg/org-faq.html#YASnippet
#+begin_src emacs-lisp
(defun yas/org-very-safe-expand ()
  (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))

(add-hook 'org-mode-hook
          (lambda ()
            ;; yasnippet (using the new org-cycle hooks)
            (make-variable-buffer-local 'yas/trigger-key)
            (setq yas/trigger-key [tab])
            (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
            (define-key yas/keymap [tab] 'yas/next-field)))
#+end_src
** Flymake
*** Prevent popups on OS X
http://stackoverflow.com/a/9885264/745
#+begin_src emacs-lisp
(setq flymake-gui-warnings-enabled nil)
#+end_src
*** For python
#+begin_src emacs-lisp
(defun flymake-create-temp-in-system-tempdir (filename prefix)
  (make-temp-file (or prefix "flymake")))

(when (load "flymake" t)
  (defun flymake-pyflakes-init ()
    (let* ((temp-file (flymake-init-create-temp-buffer-copy
		       'flymake-create-temp-in-system-tempdir))
	   (local-file (file-relative-name
			temp-file
			(file-name-directory buffer-file-name))))
      (list "pyflakes" (list local-file))))

  (add-to-list 'flymake-allowed-file-name-masks
	       '("\\.py\\'" flymake-pyflakes-init)))

(add-hook 'find-file-hook 'flymake-find-file-hook)
#+end_src
*** Show error under cursor
If the cursor is sitting on a flymake error, display the message in
the minibuf. Also bind C-c v to jump to next error

Originally found on http://paste.lisp.org/display/60617

#+begin_src emacs-lisp
  (defun show-fly-err-at-point ()
    "If the cursor is sitting on a flymake error, display the
  message in the minibuffer"
    (interactive)
    (let ((line-no (line-number-at-pos)))
      (dolist (elem flymake-err-info)
        (if (eq (car elem) line-no)
        (let ((err (car (second elem))))
          (message "%s" (fly-pyflake-determine-message err)))))))

  (defun fly-pyflake-determine-message (err)
    "pyflake is flakey if it has compile problems, this adjusts the
  message to display, so there is one ;)"
    (cond ((not (or (eq major-mode 'Python) (eq major-mode 'python-mode) t)))
      ((null (flymake-ler-file err))
       ;; normal message do your thing
       (flymake-ler-text err))
      (t ;; could not compile err
       (format "compile error, problem on line %s" (flymake-ler-line err)))))

  (defadvice flymake-goto-next-error (after display-message activate compile)
    "Display the error in the mini-buffer rather than having to mouse over it"
    (show-fly-err-at-point))

  (defadvice flymake-goto-prev-error (after display-message activate compile)
    "Display the error in the mini-buffer rather than having to mouse over it"
    (show-fly-err-at-point))

  (defadvice flymake-mode (before post-command-stuff activate compile)
    "Add functionality to the post command hook so that if the
  cursor is sitting on a flymake error the error information is
  displayed in the minibuffer (rather than having to mouse over
  it)"
    (set (make-local-variable 'post-command-hook)
         (cons 'show-fly-err-at-point post-command-hook)))

  (defun my-flymake-show-next-error()
    (interactive)
    (flymake-goto-next-error)
  ;;  (flymake-display-err-menu-for-current-line))
    )

  (global-set-key (kbd "C-c v") 'my-flymake-show-next-error)
#+end_src

** IBuffer
http://martinowen.net/blog/2010/02/tips-for-emacs-ibuffer.html
*** Bind to C-x C-b
#+begin_src emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+end_src
*** Misc config
Avoid prompts when killing buffers
#+begin_src emacs-lisp
(setq ibuffer-expert t)
#+end_src

Hide empty groups
#+begin_src emacs-lisp
(setq ibuffer-show-empty-filter-groups nil)
#+end_src
*** Configure groups
#+begin_src emacs-lisp
(setq ibuffer-saved-filter-groups
      '(("emacs-config" (or (filename . ".emacs.d")
                            (filename . "emacs-config")))
        ("Org" (mode . org-mode))
        ("Python" (mode . python-mode))
        ("Jabber" (name . "jabber\*"))
        ("Help" (or (name . "\*Help\*")
                    (name . "\*Apropos\*")
                    (name . "\*info\*")))))
#+end_src
*** Fix find-file key override
ido'ify the overridden find-file shortcut, which starts ifo-find-file
in the same directory as the file under the cursor

From http://www.emacswiki.org/emacs/InteractivelyDoThings

#+begin_src emacs-lisp
(require 'ibuffer)
(defun ibuffer-ido-find-file ()
  "Like 'ido-find-file', but default to the directory of the buffer at point."
  (interactive
   (let ((default-directory (let ((buf (ibuffer-current-buffer)))
			      (if (buffer-live-p buf)
				  (with-current-buffer buf
				    default-directory)
				default-directory))))
     (ido-find-file-in-dir default-directory))))

(define-key ibuffer-mode-map "\C-x\C-f" 'ibuffer-ido-find-file)
#+end_src

** smex
Weighted ido'ish M-x enhancement
https://github.com/nonsequitur/smex

Setup:
#+begin_src emacs-lisp
(require 'smex)
(smex-initialize)
#+end_src

Key bindings:
#+begin_src emacs-lisp
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)
#+end_src

Original M-x bound to C-c C-c M-x:
#+begin_src emacs-lisp
(global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)
#+end_src

** rib-mode
For editing renderman'ish RIB files
#+begin_src emacs-lisp
(require 'rib-mode)
(add-to-list 'auto-mode-alist '("\\.rib$" . rib-mode))
#+end_src
** escreen
http://blog.nguyenvq.com/2011/03/07/escreen-instead-of-elscreen-for-screen-like-features-in-emacs/
*** Load
#+begin_src emacs-lisp
(load "escreen")
(escreen-install)
#+end_src
*** Bind prefix to C-z
#+begin_src emacs-lisp
(setq escreen-prefix-char "\C-z")
(global-set-key escreen-prefix-char 'escreen-prefix)
#+end_src
** uniqify buffer names
http://tsengf.blogspot.com/2011/06/distinguish-buffers-of-same-filename-in.html
#+begin_src emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'post-forward-angle-brackets)
#+end_src
** Scroll view by lines
#+begin_src emacs-lisp
(global-set-key (kbd "<M-up>") (lambda () (interactive) (scroll-down 1)))
(global-set-key (kbd "<M-down>") (lambda () (interactive) (scroll-up 1)))
#+end_src
** tempbuf
Automatic removal of unused buffers
http://www.emacswiki.org/emacs/TempbufMode
*** Enable mode
#+begin_src emacs-lisp
(require 'tempbuf)
#+end_src
*** Enable for specific modes
#+begin_src emacs-lisp
(add-hook 'buffer-list 'turn-on-tempbuf-mode)
(add-hook 'dired-mode-hook 'turn-on-tempbuf-mode)
#+end_src
** yaml-mode
https://github.com/yoshiki/yaml-mode
#+begin_src emacs-lisp
(autoload 'yaml-mode "yaml-mode" nil t)
(add-to-list 'auto-mode-alist '("\\.yaml$" . yaml-mode))
(add-to-list 'auto-mode-alist '("\\.yml$" . yaml-mode))
#+end_src
** clear shell
Clear inferior-python shell etc
#+begin_src emacs-lisp
(defun clear-shell ()
  (interactive)
  (let ((comint-buffer-maximum-size 0))
    (comint-truncate-buffer)))
#+end_src
** Mark word under cursor
M-@ to highlight word under cusror

#+begin_src emacs-lisp
(defun mark-word-under-cursor ()
  (interactive)
  (backward-word)
  (mark-word))

(global-set-key [(meta @)] 'mark-word-under-cursor)
#+end_src
** Search word under cusror
M-# for vim-ish search word under cursor
#+begin_src emacs-lisp
(defvar isearch-initial-string nil)

(defun isearch-set-initial-string ()
  (remove-hook 'isearch-mode-hook 'isearch-set-initial-string)
  (setq isearch-string isearch-initial-string)
  (isearch-search-and-update))

(defun isearch-forward-at-point (&optional regexp-p no-recursive-edit)
  "Interactive search forward for the symbol at point."
  (interactive "P\np")
  (if regexp-p (isearch-forward regexp-p no-recursive-edit)
    (let* ((end (progn (skip-syntax-forward "w_") (point)))
           (begin (progn (skip-syntax-backward "w_") (point))))
      (if (eq begin end)
          (isearch-forward regexp-p no-recursive-edit)
        (setq isearch-initial-string (buffer-substring begin end))
        (add-hook 'isearch-mode-hook 'isearch-set-initial-string)
        (isearch-forward regexp-p no-recursive-edit)))))

(global-set-key (kbd "M-#") 'isearch-forward-at-point)
#+end_src
** Home between beginning of line or indentation
#+begin_src emacs-lisp
(defun beginning-of-line-or-indentation ()
  "move to beginning of line, or indentation"
  (interactive)
  (if (bolp)
      (back-to-indentation)
    (beginning-of-line)))

(global-set-key [home] 'beginning-of-line-or-indentation)
#+end_src
** end key to end of line
#+begin_src emacs-lisp
(global-set-key [end] 'end-of-line)
#+end_src
** Move lines (disabled)
#+begin_src emacs-lisp
(defun move-text-internal (arg)
  (cond
   ((and mark-active transient-mark-mode)
    (if (> (point) (mark))
        (exchange-point-and-mark))
    (let ((column (current-column))
          (text (delete-and-extract-region (point) (mark))))
      (forward-line arg)
      (move-to-column column t)
      (set-mark (point))
      (insert text)
      (exchange-point-and-mark)
      (setq deactivate-mark nil)))
   (t
    (let ((column (current-column)))
      (beginning-of-line)
      (when (or (> arg 0) (not (bobp)))
        (forward-line)
        (when (or (< arg 0) (not (eobp)))
          (transpose-lines arg))
        (forward-line -1))
      (move-to-column column t)))))

(defun move-text-down (arg)
  "Move region (transient-mark-mode active) or current line
  arg lines down."
  (interactive "*p")
  (move-text-internal arg))

(defun move-text-up (arg)
  "Move region (transient-mark-mode active) or current line
  arg lines up."
  (interactive "*p")
  (move-text-internal (- arg)))

; (global-set-key [M-up] 'move-text-up)
; (global-set-key [M-down] 'move-text-down)
#+end_src
** multi-term
#+begin_src emacs-lisp
(autoload 'multi-term "multi-term" nil t)
(autoload 'multi-term-next "multi-term" nil t)

(setq multi-term-program "/bin/bash")

(global-set-key (kbd "C-c t") 'multi-term-next)
(global-set-key (kbd "C-c T") 'multi-term) ;; create a new one
#+end_src
** fastnav
http://www.emacswiki.org/emacs/FastNav

#+begin_src emacs-lisp
(require 'fastnav)
(global-set-key "\M-z" 'zap-up-to-char-forward)
(global-set-key "\M-Z" 'zap-up-to-char-backward)
(global-set-key "\M-s" 'jump-to-char-forward)
(global-set-key "\M-S" 'jump-to-char-backward)
(global-set-key "\M-r" 'replace-char-forward)
(global-set-key "\M-R" 'replace-char-backward)
(global-set-key "\M-i" 'insert-at-char-forward)
(global-set-key "\M-I" 'insert-at-char-backward)
(global-set-key "\M-k" 'delete-char-forward)
(global-set-key "\M-K" 'delete-char-backward)
(global-set-key "\M-m" 'mark-to-char-forward)
(global-set-key "\M-M" 'mark-to-char-backward)
(global-set-key "\M-p" 'sprint-forward)
(global-set-key "\M-P" 'sprint-backward)
#+end_src
** git-blame
#+begin_src emacs-lisp
(require 'git-blame)
#+end_src
*** Show hash and start of commit message
#+begin_src emacs-lisp
(setq git-blame-prefix-format "%h %.10s:")
#+end_src
** restclient
https://github.com/pashky/restclient.el
#+begin_src emacs-lisp
(require 'restclient)
#+end_src
** markdown-mode
http://jblevins.org/projects/markdown-mode/
#+begin_src emacs-lisp
(autoload 'markdown-mode "markdown-mode.el"
   "Major mode for editing Markdown files" t)
(add-to-list 'auto-mode-alist '("\\.md$" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.markdown$" . markdown-mode))
#+end_src
** ace-jump-mode
#+begin_src emacs-lisp
(require 'ace-jump-mode)
(define-key global-map (kbd "C-c SPC") 'ace-jump-mode)
#+end_src
** coffee-script mode
*** Auto-mode for .coffee
#+begin_src emacs-lisp
(require 'coffee-mode)
#+end_src
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.coffee$" . coffee-mode))
(add-to-list 'auto-mode-alist '("Cakefile" . coffee-mode))
#+end_src
*** Convention'y tab-width
#+begin_src emacs-lisp
(defun coffee-custom ()
  "coffee-mode-hook"
 (set (make-local-variable 'tab-width) 2))

(add-hook 'coffee-mode-hook
  '(lambda() (coffee-custom)))
#+end_src
** magit
git interface
http://philjackson.github.com/magit/magit.html
*** Load module
#+begin_src emacs-lisp
(autoload 'magit-status "magit" nil t)
#+end_src
*** Custom key-bindings
#+begin_src emacs-lisp
(global-set-key "\C-ci" 'magit-status)
#+end_src
** multiple-cursors
Multiple cursors, for editing multiple lines.

https://github.com/magnars/multiple-cursors.el
http://emacsrocks.com/e13.html
#+begin_src emacs-lisp
(require 'multiple-cursors)
(global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
(global-set-key (kbd "C->") 'mc/mark-next-like-this)
(global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
#+end_src
* Laptop keyboard specific stuff
* Notes
** rgb to hex function
Might be useful for modifying theme at some point

#+BEGIN_EXAMPLE
(defun rgb (r &optional g b)
  "Converts three RGB values to HTMLish hex string.

  If supplied a single value, it is treated as a greyscale value (e.g
  (rgb 255) is identical to (rgb 255 255 255)

  ELISP> (rgb 0 128 255)
  \"#0080FF\"
  ELISP> (rgb 255)
  \"#FFFFFF\"
  "
  (if (and g b)
      (format "#%02X%02X%02X" r g b)
    (format "#%02X%02X%02X" r r r)))
#+END_EXAMPLE
